apiVersion: v1
kind: Secret
metadata:
  name: movieworld-mysql-secret
  namespace: movie-prod
  labels:
    app: movieworld
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mysql-user: bW92aWV3b3JsZA==           # movieworld
  mysql-password: bW92aWV3b3JsZHBhc3M=    # movieworldpass
