apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movieworld-dev
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/<ORG>/movieworld.git
    targetRevision: main
    path: kubernetes/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: movie-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
