{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "movieworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "movieworld.labels" . | nindent 4 }}
spec:
  host: {{ .Values.istio.destinationRule.host }}
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: {{ .Values.istio.destinationRule.trafficPolicy.connectionPool.http.http1MaxPendingRequests }}
        maxRequestsPerConnection: {{ .Values.istio.destinationRule.trafficPolicy.connectionPool.http.maxRequestsPerConnection }}
    outlierDetection:
      consecutive5xxErrors: {{ .Values.istio.destinationRule.trafficPolicy.outlierDetection.consecutive5xxErrors }}
      interval: {{ .Values.istio.destinationRule.trafficPolicy.outlierDetection.interval }}
      baseEjectionTime: {{ .Values.istio.destinationRule.trafficPolicy.outlierDetection.baseEjectionTime }}
  subsets:
  {{- range .Values.istio.destinationRule.subsets }}
  - name: {{ .name }}
    labels:
      {{- toYaml .labels | nindent 6 }}
  {{- end }}
{{- end }}
