apiVersion: v1
kind: Service
metadata:
  name: {{ include "movieworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "movieworld.labels" . | nindent 4 }}
    app: {{ include "movieworld.name" . }}
    service: {{ include "movieworld.name" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ .Values.application.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.application.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "movieworld.selectorLabels" . | nindent 4 }}
    app: {{ include "movieworld.name" . }}
