apiVersion: v1
kind: Secret
metadata:
  name: {{ include "movieworld.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "movieworld.labels" . | nindent 4 }}
type: Opaque
data:
  database-username: {{ .Values.database.username | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
