apiVersion: v1
kind: Secret
metadata:
  name: movieworld-secrets
  namespace: movie-dev
type: Opaque
data:
  # These are base64 encoded values
  # echo -n "moviereview" | base64
  database-username: YWRtaW4=  #admin
  # echo -n "password" | base64
  database-password: YWRtaW4xMjM=  #admin123

