apiVersion: v1
kind: Service
metadata:
  name: movieworld
  namespace: movie-dev
  labels:
    app: movieworld
    service: movieworld
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/actuator/prometheus"
  #   prometheus.io/port: "9091"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9091
    protocol: TCP
    name: http
  selector:
    app: movieworld
