apiVersion: v1
kind: Service
metadata:
  name: movieworld-mysql
  namespace: movie
  labels:
    app: movieworld-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: movieworld-mysql
  type: ClusterIP
