apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-ebs
provisioner: pd.csi.storage.gke.io
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  type: pd-balanced
  fsType: ext4
  encrypted: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movieworld-mysql-pvc
  namespace: movie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-ebs
  resources:
    requests:
      storage: 1Gi
      